### ISSUE TITLE
Improving performance

### ISSUE THREAD

**Issue by rsanchezgarc** [scipion-em/scipion-em-sphire#11]
Nowadays, cryolo is, by default, picking each micrograph as a job, which is highly inefficient, as the deep model needs to be loaded to gpu in each gpu. One easy fixup will be to increase the default batch size (streaming tab) to a bigger number (eg. 32 for streaming and equal to the number of micrographs in static mode), otherwise, we are wasting gpu.

**Comment by delarosatrevin** [comment]
I agree with the idea of increasing the default batch size, but maybe a bit small (e.g 10), so that one can see how it is picking quickly, without waiting too mucho.

**Comment by rsanchezgarc** [comment]
Then 16, powers of 2 are always better when dealing with this kind of stuff

**Comment by pconesa** [comment]
this is done, but not released yet with 16 as default value.
