### ISSUE TITLE
Picking protocol does not use all GPUs

### ISSUE THREAD

**Issue by vabrishami** [scipion-em/scipion-em-sphire#12]
I was trying to run Cryolo picking test in Scipion with five threads and GPU list: 0 1 2 3. However, I noticed it just uses one GPU device. I think it is because we use the same parallelization logic as other picking methods like XMIPP. Here I attached the commands from Scipion:

cryolo_predict.py -c XX.json  -w XX.h5  -i XX/tmp/micrographs_1-10/ -o XX/tmp/micrographs_1-10/ -t 0.300 -g 3
cryolo_predict.py -c XX.json  -w XX.h5  -i XX/tmp/micrographs_11-20/ -o XX/tmp/micrographs_11-20/ -t 0.300 -g 2

**Comment by pconesa** [comment]
thanks @vabrishami. We will have a look at this.

**Comment by delarosatrevin** [comment]
Hi @vabrishami 
What is the 'batch size' in the Streaming tab? If it is 0 (which mean all micrographs) then probably you will have a single step, that will end up in only one GPU. So, I recommend setting the value to a number such as 16 or 32. 
I have run some cryolo jobs recently and I see that the -g option is correctly set alternatively to 0 and 1.

**Comment by azazellochg** [comment]
@vabrishami if you have 4 gpus you need to have at least 4 batches. In the command you show you only have 2 batches, so you need to reduce batch size
