### ISSUE TITLE
Add Cinderella method in its own protocol.

### ISSUE THREAD

**Issue by dmaluenda** [scipion-em/scipion-em-sphire#13]
Add Cinderella protocol to the plugin would be nice.

It seems no so hard, its installation is very similar to crYOLO ([see installation doc](http://sphire.mpg.de/wiki/doku.php?id=auto_2d_class_selection)). While, for using, it can take .mrcs as input ([see tutorial doc](http://sphire.mpg.de/wiki/doku.php?id=auto2d_tutorial)).

**Comment by pconesa** [comment]
We have tested this and is not rendering nice results with relion or xmipp averages...with the current generic model (trainned with isac averages) I don't see it very useful.

**Comment by pconesa** [comment]
Yep, I think it can. Maybe we can implement the training and keep training it locally (with some users collaboration) and release it in a future version.

**Comment by JorMaister** [comment]
For the training, I think it should be tested first to check if it works correctly and if the resulting model works fine. In the SPHIRE wiki for Cinderella they say that the current available model was trained with 19 data sets, so I suggest that the first approach should be to get, from another source, a number of data sets close to it and generate a trained model with them. But, it's not possible to know if that number is large enough to get nice results or if it needs to be higher for a generalization until it is tested.

**Comment by delarosatrevin** [comment]
Yes, I don't know if the final benefits are worth the effort. Because the final outcome is just to select good classes, that is good (if it works well) for automation, but it is not a big thing for normal processing.

**Comment by JorMaister** [comment]
Once we have the data sets, the initial test would be quick, but if the results aren't as good as expected, the process can be extended in time. Thus, I totally agree that the first thing which should be considered is if the benefits worth the effort.
