### ISSUE TITLE
Problems cryolo training

### ISSUE THREAD

**Issue by rsanchezgarc** [scipion-em/scipion-em-sphire#16]
Hello.

I have tried to train cryolo after xmipp manual picking and I am getting 2 errors,

First comes from cryolo

No image files were found.

(I think that this stdout should be analyzed and, if found scipion should report protocol error)

Second, from scipion

00067:     File "/home/ruben/app/scipion/software/lib/python2.7/site-packages/sphire/protocols/protocol_cryolo_training.py", line 234, in cryoloModelingStep
00068:       pwutils.moveFile(self._getWorkDir(self.MODEL), self.getOutputModel())
00069:     File "/home/ruben/app/scipion/pyworkflow/utils/path.py", line 233, in moveFile
00070:       copyFile(source, dest)
00071:     File "/home/ruben/app/scipion/pyworkflow/utils/path.py", line 228, in copyFile
00072:       shutil.copy(source, dest)
00073:     File "/home/ruben/app/scipion/software/lib/python2.7/shutil.py", line 133, in copy
00074:       copyfile(src, dst)
00075:     File "/home/ruben/app/scipion/software/lib/python2.7/shutil.py", line 96, in copyfile
00076:       with open(src, 'rb') as fsrc:
00077:   IOError: [Errno 2] No such file or directory: 'Runs/003119_SphireProtCRYOLOTraining/extra/model.h5'
00078:   Protocol failed: [Errno 2] No such file or directory: 'Runs/003119_SphireProtCRYOLOTraining/extra/model.h5'

Peeking in the extra directory, I see the training mics but the training annotations folders seems empty. Any idea of what is going on?

**Comment by delarosatrevin** [comment]
Hi @rsanchezgarc, I will recommend you until @pconesa review and merge PR #15 where some updates are done in cryolo, both in the plugin and the binary supported.

**Comment by rsanchezgarc** [comment]
Ok. 
Then I will wait for the PR. I am closing this issue then
