### ISSUE TITLE
Error out of index streaming

### ISSUE THREAD

**Issue by rsanchezgarc** [scipion-em/scipion-em-sphire#18]
I am getting this error when continuing the protocol. I guess that it happens when the batch size for streaming is not divisible

01800:     File "/usr/local/scipion/2.0-devel/scipion/pyworkflow/protocol/protocol.py", line 186, in run
01801:       self._run()
01802:     File "/usr/local/scipion/2.0-devel/scipion/pyworkflow/protocol/protocol.py", line 237, in _run
01803:       resultFiles = self._runFunc()
01804:     File "/usr/local/scipion/2.0-devel/scipion/pyworkflow/protocol/protocol.py", line 233, in _runFunc
01805:       return self._func(*self._args)
01806:     File "/usr/local/scipion/2.0-devel/scipion/pyworkflow/em/protocol/protocol_particles_picking.py", line 280, in pickMicrographListStep
01807:       self._pickMicrographList(micList, *args)
01808:     File "/usr/local/scipion/2.0-devel/scipion/software/lib/python2.7/site-packages/sphire/protocols/protocol_cryolo_picking.py", line 169, in _pickMicrographList
01809:       workingDir = self._getTmpPath(self.getMicsWorkingDir(micList))
01810:     File "/usr/local/scipion/2.0-devel/scipion/software/lib/python2.7/site-packages/sphire/protocols/protocol_cryolo_picking.py", line 257, in getMicsWorkingDir
01811:       wd = 'micrographs_%s' % micList[0].strId()
01812:   IndexError: list index out of range
01813:   Protocol failed: list index out of range
01814:   FAILED: pickMicrographListStep, step 19

**Comment by delarosatrevin** [comment]
I'm still experiencing this issue, any progress???

```
pyworkflow: 3.0.7
plugin: sphire
plugin v: 3.0.5
```

**Comment by pconesa** [comment]
Thanks both! We need to look at this

**Comment by JorMaister** [comment]
Thanks both for reporting.
@delarosatrevin, does the problem exists in plugin version 3.0.6?
@rsanchezgarc, which version of the plugin are you using?

**Comment by delarosatrevin** [comment]
@JorMaister, see my comment here from two weeks ago.

**Comment by delarosatrevin** [comment]
@JorMaister I don't have time now to test with the new plugin version, but I have seen a similar error message in Relion streaming protocols. So it might be in the base code.
