### ISSUE TITLE
Critical bug in Cryolo picking validate() method

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-sphire#21]
There is a missing parenthesis here: 
https://github.com/scipion-em/scipion-em-sphire/blob/master/sphire/protocols/protocol_cryolo_picking.py#L243
and in a couple lines below. This cause an error in the validate method that prevents the protocol from running.

**Comment by pconesa** [comment]
I'm today on a MAC, not able to test this. Will do on Monday.
