### ISSUE TITLE
cryolo manual pick

### ISSUE THREAD

**Issue by smallelephant9516** [scipion-em/scipion-em-sphire#27]
Hi guy,
Thanks for your developing such great software, just a small question, when will the cryolo support manual picking from the relion star file instead of just the box file from eman2. I think if this could support relion manual picking, then, more people will be beneficial from it.

**Comment by azazellochg** [comment]
Hi, @smallelephant9516  I'm not sure I understand your question. Cryolo training inside scipion can be done with any coordinates format, including eman box and relion star. There is no manual picking in cryolo as the whole purpose of the picker is to automate it.

**Comment by smallelephant9516** [comment]
@azazellochg Thanks for your reply, I use the the cryolo only without the scipion, that probably the reason why I didn't find any way in cryolo to accept the relion star file.
