### ISSUE TITLE
Cryolo picking fails when using version 1.6.1 (ValueError: too many values to unpack)

### ISSUE THREAD

**Issue by andreanans** [scipion-em/scipion-em-sphire#29]
Hi,

I started testing the latest version of Cryolo (1.6.1) in Scipion and while training works, the picking functionality crashes. If I revert to 1.5.6 the picking works. This is part of the log that contains the error:

00059:   1902 particles in total has been found ( 6 seconds)
00060:   Deleted 20 particles as they were not fully immersed in the micrograph
00061:   Deleted 0 particles as they were out of specified size range
00062:   #####################################
00063:   
00064:   ## Particle diameter distribution ##
00065:   MEAN: 194 px
00066:   SD: 9 px
00067:   25%-Quantile: 189 px
00068:   50%-Quantile: 195 px
00069:   75%-Quantile: 200 px
00070:   Wrote particle size distribution summary to Runs/007346_SphireProtCRYOLOPicking/tmp/micrographs_1-10/DISTR/size_distribution_summary_20200403-150846.txt
00071:   Wrote plot of particle size distribution to Runs/007346_SphireProtCRYOLOPicking/tmp/micrographs_1-10/DISTR/size_distribution_20200403-150846.png
00072:   
00073:   ## Particle confidence distribution ##
00074:   Wrote confidence distribution summary Runs/007346_SphireProtCRYOLOPicking/tmp/micrographs_1-10/DISTR/confidence_distribution_summary_20200403-150846.txt
00075:   Wrote confidence distribution to Runs/007346_SphireProtCRYOLOPicking/tmp/micrographs_1-10/DISTR/confidence_distribution_20200403-150846.png
00076:   
00077:   #####################################
00078:   mv Runs/007346_SphireProtCRYOLOPicking/tmp/micrographs_1-10/CBOX/* Runs/007346_SphireProtCRYOLOPicking/tmp/outputCBOX/
00079:   FINISHED: pickMicrographListStep, step 2
00080:     2020-04-03 15:08:47.066938
00081:   Reading coordinates from mics: 1,2,3,4,5,6,7,8,9,10
00082:   Traceback (most recent call last):
00083:     File "/home/andrean/scipion_2.0/pyworkflow/protocol/protocol.py", line 186, in run
00084:       self._run()
00085:     File "/home/andrean/scipion_2.0/pyworkflow/protocol/protocol.py", line 1289, in _run
00086:       self._runSteps(startIndex)
00087:     File "/home/andrean/scipion_2.0/pyworkflow/protocol/protocol.py", line 1161, in _runSteps
00088:       self._stepsCheckSecs)
00089:     File "/home/andrean/scipion_2.0/pyworkflow/protocol/executor.py", line 133, in runSteps
00090:       stepsCheckCallback()
00091:     File "/home/andrean/scipion_2.0/pyworkflow/em/protocol/protocol_particles_picking.py", line 302, in _stepsCheck
00092:       self._checkNewOutput()
00093:     File "/home/andrean/scipion_2.0/pyworkflow/em/protocol/protocol_particles_picking.py", line 401, in _checkNewOutput
00094:       newDoneUpdated = self._updateOutputCoordSet(newDone, streamMode)
00095:     File "/home/andrean/scipion_2.0/pyworkflow/em/protocol/protocol_particles_picking.py", line 463, in _updateOutputCoordSet
00096:       self.readCoordsFromMics(outputDir, micDoneList, outputCoords)
00097:     File "/home/andrean/scipion_2.0/software/lib/python2.7/site-packages/sphire/protocols/protocol_cryolo_picking.py", line 221, in readCoordsFromMics
00098:       yFlipHeight=yFlipHeight)
00099:     File "/home/andrean/scipion_2.0/software/lib/python2.7/site-packages/sphire/convert.py", line 152, in readMicrographCoords
00100:       for x, y, score in reader.iterCoords():
00101:     File "/home/andrean/scipion_2.0/software/lib/python2.7/site-packages/sphire/convert.py", line 92, in iterCoords
00102:       for x, y, _, _, score in reader:
00103:   ValueError: too many values to unpack

**UPDATE**: Looks like the format of the CBOX file has 2 extra columns. 
Old version has 5 columns:

CoordX CoordY BoxsizeX BoxsizeY Confidence

New version has 7 columns:

CoordX CoordY BoxsizeX BoxsizeY Confidence EstimatedDiameterX EstimatedDiameterY

**Comment by JorMaister** [comment]
Hi @andreanans,
Sorry for the delay. That should have been solved with the last pull request. If not, please contact me.
jjimenez@cnb.csic.es

**Comment by andreanans** [comment]
Hi, if we installed from the binary, how do we update it? Do I just update the plugin?

**Comment by JorMaister** [comment]
Hi @andreanans,
Can you provide me a little context? Are you working with Scipion 3?

**Comment by andreanans** [comment]
Hi, we're running Scipion v2.0 (2019-04-23) and it was installed on our cluster from the binaries. We periodically update the plugins but that's it. How do you recommend we update Scipion 2.0 so it works with cryolo 1.6.1?

**Comment by JorMaister** [comment]
Thank you @andreanans,
Sphire plugin (with cryolo 1.6.1) is now done for Scipion3, which is in development now. I'm going to prepare an updated version of it for Scipion2. I hope to have it ready no longer than tomorrow. I'll inform you once it is ready. Then, you'll only have to install it in Scipion from the plugin manager. I can help you with that, if you need it, too. Is it ok for you?

**Comment by andreanans** [comment]
Hi @JorMaister, that would be great to have an updated plugin for Scipion 2.0 Thanks so much for the fast response.

**Comment by JorMaister** [comment]
Hi @andreanans, the plugin updated is almost ready, I'm waiting for the changes approval, so I can upload it to Pypi and then it will be ready. I'll inform you by then.

**Comment by JorMaister** [comment]
Hi @andreanans,
Plugin scipion-em-sphire 1.4.0 (which contains crYOLO 1.6.1) has been oficially released. I suggest you install it directly from the plugin manager. It should appear there. If you have any problem, please let me know. 
Have a nice weekend!

**Comment by andreanans** [comment]
Thanks! I'll give it a try!

**Comment by andreanans** [comment]
Hi @JorMaister,
The new Sphire plugin for Scipion 2.0 works well. thank you!

**Comment by JorMaister** [comment]
Hi @andreanans.
Glad to read it!
Anything, let us know.
