### ISSUE TITLE
Write out box files with original filename?

### ISSUE THREAD

**Issue by andreanans** [scipion-em/scipion-em-sphire#8]
Hi,

I noticed that cryolo outputs .box files as coordinates but they have been renamed to mic1, mic 2 etc. It would be super helpful if the box files retained the original name in case users want to move into Relion standalone etc.

**Comment by delarosatrevin** [comment]
Hi, yes, we decided to go for shorter names here. I would prefer to keep like that (to avoid really long filenames with path included). Maybe I should consider an open issue of a general ' relion - export coordinates protocol' where the user could decide to choose the output file names. What do you think?

**Comment by andreanans** [comment]
Yes it would be super helpful to have a general relion export coordinates function to write out star files with the full micrograph name. 

One workaround we are using at the moment is to run a relion extract with a small box size (2x2). We take the *coords.star file to use in relion standalone. However we have to do some renaming and remove the 'coords' part of the filename.

**Comment by delarosatrevin** [comment]
Ok, thanks again for the feedback. I think I will close this issue and raise the priority of the relion - export coordinates that has already been proposed here: https://github.com/scipion-em/scipion-em-relion/issues/76
