### ISSUE TITLE
Cryolo training for tomography

### ISSUE THREAD

**Issue by brodriguezdefrancisco** [scipion-em/scipion-em-sphire#80]
Hello,
We have been discussing whether would be possible to adapt the _sphire - cryolo training_ protocol to tomography. Currently there is a version of _sphire - cryolo tomo picking_ but nothing else.

Best,
Borja

**Comment by azazellochg** [comment]
IMHO, It's better to have a separate protocol, as not everyone wants to import tomo code

**Comment by delarosatrevin** [comment]
I agree with Grigory to have a separate protocol.

**Comment by azazellochg** [comment]
done in #90
