### ISSUE TITLE
select model.h5 generated externally?

### ISSUE THREAD

**Issue by andreanans** [scipion-em/scipion-em-sphire#9]
Hi,

It would be helpful if we could use a training model that was generated previously in cryolo outside of scipion. At the moment we can only select a training session created within scipion or the general model indicated in the scipion.conf file. At the moment we are using the CRYOLO_GENERIC_MODEL variable in order to use our own training models.

Thanks

Andrea

**Comment by pconesa** [comment]
thanks @andreanans , we are now talking about this and @delarosatrevin is keen of somehow "importing" models into scipion and use them.

**Comment by delarosatrevin** [comment]
@andreanans I have implemented the protocol to import existing training models for crYOLO. Once we merge that PR, would be great if you can give a try and provide feedback.
